Int. No. 493
 
By Council Members Kallos, Cabrera, Constantinides, Gentile, Johnson, Levine, Palma, Richards, Rose, Rodriguez, Lander and Levin
 
 
A Local Law to amend the New York city charter, in relation to expanding agency based voter registration to additional city agencies.
 
 
Be it enacted by the Council as follows:
 
      Section 1. The text of section 1057-a of the New York city charter prior to subdivision one is amended to read as follows:
Each agency designated as a participating agency under the provisions of this section shall implement and administer a program of distribution of voter registration forms pursuant to the provisions of this section. The following offices are hereby designated as participating voter registration agencies: The administration for children's services, the board of standards and appeals, the business integrity commission, the city clerk, the civilian complaint review board, the commission on human rights, community boards, the conflicts of interest board, the department of small business services, the department of the aging, the department of buildings, the department of citywide administrative services, the department of city planning, the department of consumer affairs, the department of correction, the department of cultural affairs, the department of environmental protection, the department of finance, the department of health and mental hygiene, the department of homeless services, the department of housing preservation and development, the department of parks and recreation, the department of probation, the department of records and information services, the taxi and limousine commission, the department of transportation, [and] the department of youth and community development, the fire department, the human resources administration, the landmarks preservation commission, the office of administrative trials and hearings, the office of emergency management, the office of immigrant affairs, and the police department. Participating agencies shall include a mandate in all new or renewed agreements with those subcontractors having regular contact with the public in the daily administration of their business to follow the guidelines of this section. Such participating agencies shall be required to offer voter registration forms to all persons together with written applications for services, renewal or recertification for services and change of address relating to such services; provided however that this section shall not apply to services that must be provided to prevent actual or potential danger to the life, health, or safety of any individual or of the public. Such agencies [may] shall provide assistance to applicants in completing voter registration forms, if so requested. Such agencies [may] shall also[, in their discretion,] receive and transmit the completed application form from any applicants who [wish] request to have such form transmitted to the board of elections for the city of New York.
      §2. Paragraph c of subdivision 3 of section 1057-a of the New York city charter is amended to read as follows:
c. transmit any completed forms collected [in their discretion] by such agency to the board of elections of the city of New York within two weeks of the receipt of such completed forms at the participating agency. If a completed form is [accepted] collected within five days before the last day for registration to vote in a citywide election, such completed form shall be transmitted by the participating agency to the board of elections of the city of New York not later than five days after the date of acceptance.
§3. This local law shall take effect thirty days after its enactment.
