Int. No. 508
 
By Council Members Kallos, Reynoso, Richards, Dromm, Levine, Rosenthal, Levin, Lander, Rodriguez, Rose, Menchaca, Cabrera, Chin, Constantinides, Dickens, Johnson, Koo, Lancman, Mendez and Miller
 
 
A Local Law to amend the New York city charter, in relation to allowing online voter registration.
 
 
Be it enacted by the Council as follows:
Section 1. Chapter 46 of the New York city charter is amended by adding a new section 1057-c to read as follows:
§1057-c Online voter registration. a. The board of elections shall provide a secure website that allows any eligible resident of the city of New York to confidentially submit through such website the information collected on a voter registration application form pursuant to section 5-210 of the election law to the board of elections for the purposes of registering to vote or updating his or her voter registration. As a part of such submission, the website shall allow such resident to view the notices contained on a voter registration application form pursuant to section 5-210 of the election law. Upon receipt of such information, the board of elections shall process it in the same manner as an application form submitted by mail pursuant to section 5-210 of the election law, subject to the requirements of section 303(b) of the help america vote act of 2002, except that the absence of a written signature shall not render such an application incomplete or otherwise preclude the registration of an eligible individual. For the purposes of this section, the term "board of elections" shall mean the New York city board of elections.
b. For any eligible individual attempting to register or update his or her registration at the website provided pursuant to this section who submits information that will not be processed as valid for the next election, such website shall notify him or her at the time of submission that the registration or update will not take effect for the next election.
c. The board of elections shall develop procedures to enable an eligible individual who submits an application using the website provided pursuant to this section, and whose application lacks a signature, to provide a signature at the polling place, or by submitting an application for an absentee ballot, before voting. The board of elections may require an individual who has not provided a signature before arriving at a polling place or submitted an absentee ballot to present a current and valid photo identification or a copy of a current utility bill, bank statement, government check, paycheck, or other government document that shows the name and address of such individual prior to voting.
§2. This local law shall take effect one year after its enactment, provided, however, that the New York city board of elections shall take such actions prior to such time as are necessary for timely implementation of this local law.
